services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:${HA_TAG:-stable}
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=${TZ:-America/Santiago}
    volumes:
      - ./config:/config

